name: prod_random
services:
  discord-bot-1:
    container_name: app-name-1_prod-random
    image: random/purgs-toe-facts:latest
    restart: always
    networks:
      - prod_random_server
    environment:
      DOTENV_KEY: ${DOTENV_KEY}

networks:
  prod_random_server:
    external: true
