name: local_app
services:
  discord-bot-1:
    container_name: local_app-name-1
    build:
      context: .
    env_file:
      - .env
    networks:
      - local_server

networks:
  local_server:
    external: true
