name: stage_appcontainer
services:
  discord-bot-1:
    container_name: app-name_stage-appcontainer
    image: appcontainer/appname:next
    restart: always
    networks:
      - stage_server
    environment:
      DOTENV_KEY: ${DOTENV_KEY}
    volumes:
      - ./logs:/app/logs
      - type: bind
        source: /run/redis-badge-buddy/redis-server-badge-buddy.sock
        target: /app/redis/redis.sock

networks:
  stage_server:
    external: true
