#file: noinspection YAMLSchemaValidation
name: deploy prod
on:
  push:
    branches:
      - main
env:
  GH_TOKEN: ${{ github.token }}
jobs:
  deploy-prod:
    runs-on: ubuntu-latest
    environment: prod
    permissions:
      contents: write
      pull-requests: write
      repository-projects: read
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: pnpm/action-setup@v2
      - uses: actions/setup-node@v3
        with:
          node-version-file: 'package.json'
          cache: 'pnpm'
          cache-dependency-path: 'pnpm-lock.yaml'
      - run: git config user.name "github-action[bot]"
      - run: git config user.email "<>"
      - run: pnpm install --frozen-lockfile
      - run: pnpm lint
      - run: pnpm test:cov
      - run: git push --follow-tags
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}
      - name: Build Docker and Push
        uses: docker/build-push-action@v5
        with:
          push: true
          context: .
          load: true
          tags: |
            ${{ secrets.DOCKER_USERNAME }}/purgs-toe-facts:latest
          cache-from: type=gha
          cache-to: type=gha,mode=max
      - run: docker cp $(docker run -d --rm ${{ secrets.DOCKER_USERNAME }}/purgs-toe-facts:latest):/app/dist ./dist
      - uses: vimtor/action-zip@v1
        with:
          files: dist/ CHANGELOG.md LICENSE.md README.md package.json
          dest: dist.zip
      - name: Transfer compose.prod.yml
        uses: appleboy/scp-action@v0.1.4
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_KEY }}
          passphrase: ${{ secrets.SSH_PASSPHRASE }}
          port: ${{ secrets.SSH_PORT }}
          source: "compose.prod.yml"
          target: "${{ secrets.APP_PATH_PRODUCTION }}"
      - name: Deploy to server
        uses: appleboy/ssh-action@v1.0.0
        env:
          DOTENV_KEY: ${{ secrets.DOTENV_KEY_PRODUCTION }}
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_KEY }}
          passphrase: ${{ secrets.SSH_PASSPHRASE }}
          port: ${{ secrets.SSH_PORT }}
          envs: DOTENV_KEY
          script: |
            cd ${{ secrets.APP_PATH_PRODUCTION }}
            docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_TOKEN }}
            docker compose -f compose.prod.yml pull
            docker compose -f compose.prod.yml stop
            DOTENV_KEY=$DOTENV_KEY docker compose -f compose.prod.yml up -d
